### ISSUE TITLE
Internet objects as part of the Citation list?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#34]
Could another item be added to the Citations list? A simple consolidated list of Internet objects in a single text box could be quite useful. Since it is undated, float it to the top of the citations.

Make each row a hot-linked Description, with click to follow (launch a client app - Browser/eMail), right-click to edit or Add object records. 

It would be helpful if the browser Windows were 'named' (perhaps by row #?) and updated instead spawned endless new Windows.

Another (questionable) refinement might be to associate a Character with each Type of record and use those instead of bulleting the list:

WebSearch = Character “🔍” (U+1F50D). 🔍. Name: Left-Pointing Magnifying Glass

Email = unicode “✉” U+2709 Envelope Unicode Character - Compart
 📧 E-Mail Symbol Emoji U+1F4E7

Web  = Unicode Character “🌐” (U+1F310) globe with meridians

📡 Ftp Satellite Antenna
Unicode number:
HTML-code:
U+1F4E1
&#128225;

https://gramps-project.org/wiki/index.php/Gramps_5.1_Wiki_Manual_-_Entering_and_editing_data:_detailed_-_part_1#Internet_Address_Editor

**Comment by cdhorn** [comment]
You saw the URL support in the action menu for a person to add/edit/launch/remove right?  Citations and sources do not yet have URL support though I seem to recall seeing a PR or discussion about adding it though. If added the code will detect and expose them in the action menu.

Or you are not referring to URL objects for citations, just the person but directly expose them in a frame in the citation list?

Anyway this makes me think might be a good feature to parse all the notes and extract any and expose them for quick access. That would be something a bit different but useful I think.

**Comment by emyoulation** [comment]
My hope for the future is that Gramps will add something like the Search Engine customizations in browsers (see [Chrome search strings](https://www.techrepublic.com/google-amp/article/pro-tip-add-custom-search-engines-in-chrome-for-more-efficient-searching/) or ) 

With the ideas that if a Source or Repository had a parameterized SearchPatternURL attribute or standard Gramps fieldname, then it would substitute in a field value for the Child object.  Much like the WebConnect already does with Person searches using the surname, given name, & years of birth/death.)

As an example, I have 3 FindAGrave sources: Memorial, Cemetery & Graver. I put in the permanent IDs as the page number for a citation under those sources. In the years that I've been using Gramps, FindAGrave has changed the way they pass ID parameters at least 4 times. But the IDs have stayed the same.

`https://www.findagrave.com/memorial/<vol/page>/<last>-<first>`


`https://www.findagrave.com/cemetery/<vol/page>/<name>`

`https://www.findagrave.com/user/profile/<vol/page>`

The CitationPattern might be:
`<a href=""<SearchPatternURL>"">FindAGrave memorial "<vol/page>"</a> - "<last>", "<call>" "<birthyear>"-"<deathyear>`'

or I might decide to have a standard FindAgrave button/icon as a media item and create a string that links that instead.

**Comment by cdhorn** [comment]
Yes we could add a simple templating engine to support schemes like that. I will keep that in mind. My initial thought is something like that is outside scope of the view itself and best handled in Gramps core.

**Comment by emyoulation** [comment]
Agreed. It needs to be elsewhere. 

I guess I'm too excited by this feature and am straying out of scope.

**Comment by cdhorn** [comment]
Closing this in lieu of commit 03db7d3134d466423aa5bf2643fc3c76492e88d3 which adds url group support with an option to include http urls parsed from note records.
