### ISSUE TITLE
Always Show Roles for Timeline shows "primary" on family member events

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#41]
After enabling the Configuration for Timelines to "show roles always not just secondary events", the Timeline panel shows "primary" for events where the a family member holds the 'primary' role.  

In these timeline events, the Active Person's role (if not explicitly defined) is implicit.  They are merely a family member for that Event.  Could it display that "Implicit, family member"? Or even "Implicit role: step-brother" if the Relationship calculator is a viable option.

**Comment by cdhorn** [comment]
That's a good idea.  The timeline / event stuff will probably get refactored again soon.

**Comment by cdhorn** [comment]
Implemented in 858c1d3e8eb917ae0c3da668e285219f2acaddee

Person timeline show all roles option now shows implicit family relationships. 
Family timeline now constructs a more specific title.
When options enabled to add dated citations, media, name and address records to the person timeline they now will also show the age if that is enabled,
