### ISSUE TITLE
Configuration "Person" tab has doubled checkbox options 

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#42]
The Configuration of the Profile mode has the following Person tab checkboxes duplicated in the 1st & 2nd columns:
* Skip birth alternatives if birth found
* Skip death alternatives if death found
Selecting the checkbox in either column updates the selection state in the 1st column and ignores the state in the 2nd column.

![image](https://user-images.githubusercontent.com/69127217/125503322-d8334010-ceb1-48c0-b010-e8e535a5eea4.png)

**Comment by cdhorn** [comment]
Should be fixed by 913eb02cae24d1ac5ebc24a4d900a801f7d061ec now.
