### ISSUE TITLE
An UPDATE on Home Person is selected when the view is initially selected #40

### ISSUE THREAD

**Issue by DaveSch-gramps** [cdhorn/profileview#45]
When launching Gramps and where the Profile view is the last viewed, the Active person loads as expected.

If Gramps launches on another view (Relationships) and then the Profile view is selected, the view displays is blank. The entire person history is blank. The forward/backward arrows are grayed out. 

Loaded the most recent version 7/14 at 21:02

**Comment by cdhorn** [comment]
Commit 4db59199b3803cd080666fa6b4eec03d54411b9d handles it a little better. I need to look closer at the history handling yet at some point, other priorities at moment.

**Comment by DaveSch-gramps** [comment]
I have had a chance to install the new code. 7/17 @ 7:55

The Profile view opens on the last person accessed from the previous Gramps session. The blank screen is gone. This holds true if Gramps was opened on another person view and after a new Go history is developed.

The Go history is empty when you first open the Profile view. Moving to another view the Go history is fully populated with the RestoreHist's list at startup.  The profile view does track the new Go history after Gramps launch and after the profile view has been accessed.

What I do not understand, is that navigation issue were working on the 7/1 version.

**Comment by cdhorn** [comment]
The 7/1 version used the Gramps core `NavigationView` and `History` classes, this version no longer does, it uses the ones from Nick's `CombinedView` as they provided a much better framework. However it actually uses a further modified version of his work as his only supported navigation across `Person` and `Event` objects and this view now handles all of them with the latest commit albeit a great deal of refinement is still needed.

The `History` class Nick wrote is unified and so tracks whatever object was accessed. In the other object specific page views the `History` is only for that specific object.  The `RestoreHist` plugin restores their history buffers if it can but not the state of the history used by this view.

I may add that in a future enhancement.  For the present time I save the last object accessed and this view should attempt to load that and use that to seed the empty history buffer. Should that fail it now falls back to trying to load what it thinks was the last accessed object from the other history buffer.

I hope I explained that okay.

**Comment by DaveSch-gramps** [comment]
Thank you for the explanation and I understand the need to have the view go from a Person view to an Event view and the need to track that history. I have often bemoaned opening the Family edit window in the Relationships view but that Family history is not tracked, So going to the Family list does not jump to the most recently edited family.

But initial/active person disconnect when first display the view (and Combined view) is disconcerting.

**Comment by DaveSch-gramps** [comment]
Congratulations. The view is now tracking the active person when view is selected!!
