### ISSUE TITLE
Request a 'Show' option for the Media Items column

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#54]
The new Media Items column does not have an option in the Layout to be turned off.  

If you prefer to not implement a Show/Hide & just support the Minimize (by clicking the Arrow or title), it still consumes the space needed to show "⏵Media Items".  Could minimizing leave off the header label text so that it gives back more screen space?

**Comment by cdhorn** [comment]
I think I just added that to some of the missing pages in the last commit. If I missed any let me know.

Please note I've _not_ been trying to make specific features "feature complete" before pushing. My main focus at moment is getting enough in place to navigate across all the objects to get a feel for what works and what doesn't and if the approach I am taking is okay or not. So there are a lot of details that will get ironed out later on.

**Comment by emyoulation** [comment]
Confirmed.  Just downloaded & installed the new commits and the new version has the feature. Thank you.

Please close this issue.
