### ISSUE TITLE
Feedback requested on config options

### ISSUE THREAD

**Issue by cdhorn** [cdhorn/profileview#57]
For anyone checking in on things here, I am interested in opinions on the configuration options. 

At the moment every page view has a separate options namespace, so you can tweak things at a ridiculously granular level. But there are sooo many now I'm thinking maybe that was not a good idea and I over did it. 

Should I change things and try to flatten things out more?

I am thinking for each object one set of options for when they are the active object for the page and then one set for when they are not the active object with a special case for person and family where parent, spouse, sibling, child would continue to be differentiated.

**Comment by emyoulation** [comment]
Well, I was thinking that your Configuration was going to be a nightmare for Weblate. And it is... overwhelming... the first time a person explores. (But in addition to my admiration for the Profile view on general, I'd like to convey my appreciation that there isn't a tab labeled like [Reports Options (2)](https://www.gramps-project.org/wiki/index.php/DescendantsLines#Options) ! Thank you VERY much for that.

I dunno if there is a lexicon of phrases that are already translated. If so, it'd save a lot of translation work to use existing labels.

And there are some truly awkward labels in there too.

**Comment by cdhorn** [comment]
> I dunno if there is a lexicon of Gramps phrases that are already translated. If so, it'd save a lot of translation work to use existing labels.

Not sure. I have not looked at it in languages other than English much at all. I did look at it in German a couple weeks back and realized I had to fix the user defined field stuff. It may need more work in that regard.

> And there are some truly awkward labels in there too.

Probably, suggestions to improve wording welcome.

With commit tonight ctrl-right click any frame to get the layout editor.

**Comment by cdhorn** [comment]
Commit 81f3b85dded17313c8fd9b47310361451b434767 does the following:

1. Refactored options name space, object frames now have one set of options if active in the header and another if in a group.
2. Refactored plugin configuration panels, all options are now in one place.
3. Fold layout editor into the configuration dialog, no longer a separate window and method to access.
4. Add warning dialog on reset to defaults, with a checkbox option to reset all options and not just the page.

Note configuration dialog is slow to load because it takes a while to build, resetting all options takes a long time while examining them all to see if any changed and need to be reset, and layout section could be better integrated with the whole.
