### ISSUE TITLE
Citation panel hotlinks cause freeze

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#59]
Using the Example.gramps file.
Navigator in Drop-Down mode
Relationships > Profile View
Configure (Shift-Crtl-C)
   ( "Configure Relationships - Profile" now automatically focuses on the Gramplet tabs.  Thank you!)
select "Show associated Citations" in Layout tab
  Close Configuration

Click on the "Imported from test2.ged" hotlinked citation title.

You have to force a close of the program
 
Cursor turns to permanent 'busy' hourglass

**Comment by cdhorn** [comment]
Yes, I am aware of this, there are 2000+ of those. 

I am unsure what to do about large numbers of objects. The view isn't really designed for "paging" so I will probably set some maximum on number of fetched objects. The list views are much much lighter and better suited for that sort of thing.

**Comment by emyoulation** [comment]
What is the goal when selecting this hotlink.

The Relationships (Profile) of the Event submode (to which the view navigated following a click on the hotlinked title of an Event in the Timeline panel) was edifying. It provided an overview of the Event & profile summary cards for everything that references that Event - clarifying how they interrelate. (Although it needs a visible control to pop back up a level to the Person profile for the Active Person.)  

I was anticipating something SIMILAR for the Citation: a summary Profile card for the Citation with Sources (perhaps with a count of Citations referencing that source & Repositories containing the source, giving scale to importance of the source), Objects that Reference the Source, Notes, Gallery, and Attributes subpanels below. 

Perhaps, in the future, someone might create a gramplet that composed a copy-ready inline/footnote/endnote/bibliography citations in one of the standard formats: MLA, Turabian/Chicago, APA, et cetera. (This would have too much utility in too many views to build into to just one view.)

**Comment by cdhorn** [comment]
At the moment the hot link on the Citation card title, which is the title of the Source record, brings you to the Source view not Citation view. It will show the Repositories the Source is in, all the Citations against that Source, and so forth. 

A double click elsewhere on the Citation frame pivots to the actual Citation view. 

A Citation is a source reference, there is only ever one Source associated with it. Actually I meant to add that frame above the Citation on the Citation view page and will fix that shortly.

I suppose I could add an option as to whether the link goes to Source or Citation view.

**Comment by cdhorn** [comment]
Option to control if the citation title links to Source or Citation page added in 1122b4696420b551e679d663ca9926f8faf3f003

**Comment by cdhorn** [comment]
Commit 72168fd085533fd26065d113ebc573fe88c1a671 adds options to limit maximum number of citations and references shown.

**Comment by cdhorn** [comment]
Should no longer occur after commit 72168fd085533fd26065d113ebc573fe88c1a671 set a cap on objects to try to display for citations and references.
