### ISSUE TITLE
Change "Profile View" label to just "Profile"

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#61]
The View is the Relationships category view.  The Profile adds a 'mode' of the View category

Review the labels in the Navigator using the Drop-down.  The other 2 modes are "Relationships" and "Combined"

Only the Geography category view's "Place Coordinate Gramplet view" has another redundant label.  It claims both an extra "Gramplet" and "view" in its label.

**Comment by cdhorn** [comment]
Good point, changed in last commit.

**Comment by cdhorn** [comment]
Actually maybe the mode name, if it stays under Relationships, should be changed to Linked.  We'll see when it's closer to a real release.
