### ISSUE TITLE
Artificially limit Note previews?

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#62]
Notes can contain megabytes. Perhaps it would be useful to have some sort of a fixed Notes card height limit available in the configuration? (Is there a way to limit how much is fetched from a note? If so, a preview mode might provide resource savings g performance advantages.)

Rather than another Tab for "Notes"and in configuration, perhaps the Layout checkbox for "Show associated notes" could change to a control inspired by the Tag display mode pop-up menu?  It might have  3 "Associated Notes display mode" options: Disabled, Preview, Full text.

**Comment by cdhorn** [comment]
Mine are generally short, I hadn't considered that others might have very large ones.  I agree some sort of preview thing is in order. 

Embedded links obviously don't work at the moment either. I didn't take time to look at the notes code that closely yet, only enough to figure out how to use the styled text buffer to display one.

**Comment by cdhorn** [comment]
Preview support added earlier in f6791f451e04335194c2f62b94cccb4c93ea109f, added options to configure it in  1122b4696420b551e679d663ca9926f8faf3f003

**Comment by emyoulation** [comment]
Please re-open.  Currently, we can configure how the Notes tiles display would be formatted.  But I cannot actually cause the Notes panel to be shown.

**Comment by cdhorn** [comment]
Hmm, this is working okay on my machine. Can you rename you .ini and see if it works with a clean one? If not any hints if running from command line when you try to display it?

**Comment by emyoulation** [comment]
It was the new Layout editor!  The Media and Notes columns were disabled by default.

I'm... not thrilled... with the idea of a 2nd spawned level to Configuration.  

But the tabbed option, draggable column ordering are both exciting.  

The stacking is confusing though.  It would make more sense if  dragging one column on top of the box of another column stacked them. And reordering of the stack was by dragging too.  I suppose you could use an empty container anytime columns were stacked so it would be obvious you could drag a column from a stacked container to the empty one to unstack it.

Please consider using a hairline border for the containers  

It is also confusing that the page layout is in columns but the ordering is in rows.  If the stacking was by dragging, you would be able to use a single checkbox to the left of the column label and that it controlled 'visibility' would be intuitively obvious.

**Comment by cdhorn** [comment]
Given my current knowledge of Gtk this was simpler to implement so it will have to do for now.

It might go away at some point and fold into being one tab on each object configuration page, we'll see.

There are too many configuration options. Ideally I'd like to pull up the configuration editor and be able to edit any of them, and not have to navigate to each separate object view to edit options for that view.
