### ISSUE TITLE
Parents and Siblings tile formatting has strange spacings

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#65]
The vertical space allocated for each "Parents and Siblings" is compact if all the other columns are minimized.  But Expanding (one extra column expanded at a time) causes huge amounts of vertical blank space to be added.  

As a representative example, expanding the Timeline Events caused the  "Parents and Siblings" Tag to span 16 rows of text in the Timeline Events. And the name to be vertically centered while spanning about 8-10 rows.

The other columns "Cited Sources", and "Spouses and Children" affect it to a lesser degree.

Also, note the horizontal indent for Events composite "Date in Place" is oddly irregular. (Could be the CSS on Windoze) It seems to be trying to add a hanging indent if the the line wraps but accidentally not "hanging".  And not vertically aligning the Event type to top of the table cell on wrapped description rows.

![image](https://user-images.githubusercontent.com/69127217/126916559-2c63ca8b-5e2a-4ad4-b917-263e9900b902.png)

**Comment by cdhorn** [comment]
Yes, I've seen both of those. I'm unsure if some of this is me misunderstanding how Gtk handles layout or bugs/quirkiness in Gtk itself.

For the word wrapping I set both left align and left justify but as you see Gtk isn't rendering that way, so I wonder if that is a Gtk issue.

I'm currently playing with adding temporary hide on collapse for the expander, it seems logical to me that if I hide it all the space should get reallocated when Gtk recalculates the layout, but a large chunk is still left unused.

**Comment by emyoulation** [comment]
Perhaps if you change the title to a single nonbreaking space of the collapsed column label?  The space requirement might drop to 2 characters wide for collapsed columns. Then rename the column label again when expanded.

**Comment by cdhorn** [comment]
No, that didn't work. Rather than hide decided to just remove it outright. Changes commited should work for most groups now though may have missed some not well tested.

**Comment by cdhorn** [comment]
Commit afc8d1e0ed69e8392ce2c9dbcc08f6eb50a8d53e should resolve the text alignment issue so I think this can be closed now.
